package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"strconv"
	"todo/db"
	"todo/graph/model"
	"todo/middleware"
	"todo/models"
	services "todo/service"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, username string, email string, password string) (string, error) {
	return services.Register(username, email, password)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (string, error) {
	return services.Login(email, password)
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, title string) (*model.Todo, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	todo := models.Todo{
		Title:     title,
		Completed: false,
		UserID:    userID,
	}

	if err := db.DB.Create(&todo).Error; err != nil {
		return nil, err
	}

	return &model.Todo{
		ID:    strconv.Itoa(int(todo.ID)),
		Title: todo.Title,
		Done:  todo.Completed,
	}, nil
}

// ToggleTodo is the resolver for the toggleTodo field.
func (r *mutationResolver) ToggleTodo(ctx context.Context, id string) (*model.Todo, error) {
	todoID, _ := strconv.Atoi(id)

	var todo models.Todo
	if err := db.DB.First(&todo, todoID).Error; err != nil {
		return nil, err
	}

	todo.Completed = !todo.Completed

	db.DB.Save(&todo)

	return &model.Todo{
		ID:    id,
		Title: todo.Title,
		Done:  todo.Completed,
	}, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (bool, error) {
	todoID, _ := strconv.Atoi(id)

	if err := db.DB.Delete(&models.Todo{}, todoID).Error; err != nil {
		return false, err
	}

	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, username string) (*model.User, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var user models.User
	if err := db.DB.First(&user, userID).Error; err != nil {
		return nil, err
	}

	user.Username = username

	if err := db.DB.Save(&user).Error; err != nil {
		return nil, err
	}

	return &model.User{
		ID:    strconv.Itoa(int(user.ID)),
		Username:  user.Username,
		Email: user.Email,
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (bool, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok {
		return false, fmt.Errorf("unauthorized")
	}

	if err := db.DB.Delete(&models.User{}, userID).Error; err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {

	userID, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	var user models.User
	if err := db.DB.First(&user, userID).Error; err != nil {
		return nil, err
	}

	var todos []models.Todo

	if err := db.DB.Where("user_id = ?", userID).Find(&todos).Error; err != nil {
		return nil, err
	}

	var gqlTodos []*model.Todo

	for _, t := range todos {
		gqlTodos = append(gqlTodos, &model.Todo{
			ID:    strconv.Itoa(int(t.ID)),
			Title: t.Title,
			Done:  t.Completed,
		})
	}

	return &model.User{
		ID:       strconv.Itoa(int(user.ID)),
		Username: user.Username,
		Email:    user.Email,
		Todos:    gqlTodos,
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}


func (r *userResolver) Todos(ctx context.Context, obj *model.User) ([]*model.Todo, error) {

	userID, _ := strconv.Atoi(obj.ID)

	var todos []models.Todo
	if err := db.DB.Where("user_id = ?", userID).Find(&todos).Error; err != nil {
		return nil, err
	}

	var result []*model.Todo

	for _, t := range todos {
		result = append(result, &model.Todo{
			ID:    strconv.Itoa(int(t.ID)),
			Title: t.Title,
			Done:  t.Completed,
		})
	}

	return result, nil
}


func (r *Resolver) User() UserResolver { return &userResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
